FROM python:3.11-slim

WORKDIR /app

COPY mcp_langgraph_app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8001

CMD ["uvicorn", "mcp_langgraph_app.mcp_server.sse_mcp_server:app", "--host", "0.0.0.0", "--port", "8001"]